"""Small, explicit RBAC policy used by the API and application services."""

from typing import ClassVar

from app.core.enums.users import MembershipRole


class PermissionService:
    _ROLE_PERMISSIONS: ClassVar[dict[str, frozenset[str]]] = {
        MembershipRole.OWNER.value: frozenset({"*"}),
        MembershipRole.ADMIN.value: frozenset({"*"}),
        MembershipRole.ACCOUNTANT.value: frozenset(
            {
                "account:create",
                "account:read",
                "account:update",
                "fiscal_year:create",
                "fiscal_year:read",
                "fiscal_year:update",
                "fiscal_period:create",
                "fiscal_period:read",
                "fiscal_period:update",
                "fiscal_period:close",
                "journal:create",
                "journal:read",
                "journal:update",
                "journal_entry:create",
                "journal_entry:read",
                "journal_entry:update",
                "journal_entry:post",
                "journal_entry:reverse",
                "journal_entry:correct",
                "financial_report:read",
                "trial_balance:read",
                "general_ledger:read",
                "comparative_balance:read",
                "bank_reconciliation:create",
                "bank_reconciliation:read",
                "bank_reconciliation:match",
                "vat:create",
                "vat:read",
                "vat:update",
                "inventory_product:create",
                "inventory_product:read",
                "inventory_product:update",
                "inventory_warehouse:create",
                "inventory_warehouse:read",
                "inventory_warehouse:update",
                "inventory_stock:receive",
                "inventory_stock:issue",
                "inventory_stock:adjust",
                "inventory_stock:transfer",
                "inventory_stock:read",
                "invoice:create",
                "invoice:read",
                "invoice:update",
                "invoice:issue",
                "credit_note:create",
                "credit_note:read",
                "payment:create",
                "payment:read",
                "treasury_bank_account:create",
                "treasury_bank_account:read",
                "treasury_bank_account:update",
                "treasury_position:read",
                "treasury_transaction:create",
                "treasury_transaction:read",
                "treasury_reconciliation:read",
                "payroll_employee:read",
                "payroll_contract:read",
                "payroll_rule_set:read",
                "payroll_period:read",
                "payroll_slip:read",
                "payroll_audit:read",
                "treasury_reconciliation:match",
                "payroll_employee:create",
                "payroll_employee:update",
                "payroll_contract:create",
                "payroll_contract:update",
                "payroll_rule_set:create",
                "payroll_period:create",
                "payroll_period:calculate",
                "payroll_period:validate",
                "payroll_period:lock",
                "payroll_period:post",
                "payroll_correction:create",
                "fixed_asset_category:create",
                "fixed_asset_category:read",
                "fixed_asset:create",
                "fixed_asset:read",
                "fixed_asset:update",
                "fixed_asset:acquire",
                "fixed_asset:commission",
                "fixed_asset_depreciation:read",
                "fixed_asset_depreciation:post",
                "fixed_asset_disposal:create",
                "audit_event:read",
                "audit_event:verify",
            }
        ),
        MembershipRole.MANAGER.value: frozenset(
            {
                "account:read",
                "fiscal_year:read",
                "fiscal_period:read",
                "journal:read",
                "journal_entry:read",
                "financial_report:read",
                "trial_balance:read",
                "general_ledger:read",
                "comparative_balance:read",
                "bank_reconciliation:read",
                "vat:read",
                "inventory_product:read",
                "inventory_warehouse:read",
                "inventory_stock:read",
                "invoice:read",
                "credit_note:read",
                "payment:read",
                "treasury_bank_account:read",
                "treasury_position:read",
                "treasury_transaction:read",
                "treasury_reconciliation:read",
                "payroll_employee:read",
                "payroll_contract:read",
                "payroll_rule_set:read",
                "payroll_period:read",
                "payroll_slip:read",
                "payroll_audit:read",
                "fixed_asset_category:read",
                "fixed_asset:read",
                "fixed_asset_depreciation:read",
                "audit_event:read",
            }
        ),
        MembershipRole.USER.value: frozenset(),
        MembershipRole.AUDITOR.value: frozenset(
            {
                "account:read",
                "fiscal_year:read",
                "fiscal_period:read",
                "journal:read",
                "journal_entry:read",
                "audit:read",
                "financial_report:read",
                "trial_balance:read",
                "general_ledger:read",
                "comparative_balance:read",
                "bank_reconciliation:read",
                "vat:read",
                "inventory_product:read",
                "inventory_warehouse:read",
                "inventory_stock:read",
                "invoice:read",
                "credit_note:read",
                "payment:read",
                "treasury_bank_account:read",
                "treasury_position:read",
                "treasury_transaction:read",
                "treasury_reconciliation:read",
                "payroll_employee:read",
                "payroll_contract:read",
                "payroll_rule_set:read",
                "payroll_period:read",
                "payroll_slip:read",
                "payroll_audit:read",
                "fixed_asset_category:read",
                "fixed_asset:read",
                "fixed_asset_depreciation:read",
                "audit_event:read",
                "audit_event:verify",
            }
        ),
    }

    @classmethod
    def role_allows(
        cls, role: str, permission: str, is_superuser: bool = False
    ) -> bool:
        allowed = cls._ROLE_PERMISSIONS.get(role, frozenset())
        return is_superuser or "*" in allowed or permission in allowed
